# Generated by Django 5.1.1 on 2024-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
